name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
    - name: Restore dependencies
      run: dotnet restore src/Jabuticaba/
    - name: Build
      run: dotnet build --no-restore src/Jabuticaba/
    - name: Test
      run: dotnet test --no-build --verbosity normal test/JabuticabaTests/
    - name: Publish Nuget Package
      run: dotnet nuget push  **/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
